# Site settings
title: jsolve.pl Solve it, Code it - blog
email: contact@jsolve.pl
authors: Tomasz Kuryłek, Łukasz Stypka
description: > # this means to ignore newlines until "baseurl:"
  Solve it, Code it
baseurl: ""
url: "http://jsolve.pl/blog"
twitter_username: jsolve
github_username:  jsolve
permalink: /:categories/:title/
paginate: 20

# Build settings
markdown: kramdown

# Serving
host: 0.0.0.0
port: 4000