# Site settings
title: jsolve.pl Solve it, Code it - blog
email: contact@jsolve.pl
authors: Tomasz Kuryłek, Łukasz Stypka
description: > # this means to ignore newlines until "baseurl:"
  Solve it, Code it
baseurl: ""
url: "http://jsolve.github.io"
twitter_username: jsolve
github_username:  jsolve
permalink: /:categories/:title/
paginate: 5

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

# Serving
host: 0.0.0.0
port: 4000